# Generated by Django 6.0.5 on 2026-05-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowerlyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time_from',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time_to',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_slot',
            field=models.CharField(choices=[('9-12', '09:00 – 12:00'), ('12-15', '12:00 – 15:00'), ('15-18', '15:00 – 18:00'), ('18-21', '18:00 – 21:00')], default='9-12', max_length=20, verbose_name='Слот доставки'),
        ),
    ]
